### ISSUE TITLE
Chrome store still at 0.8.1, and cannot auth for any service provider

### ISSUE THREAD

**Issue by Hellmark** [Cleod9/syncmarx-webext#36]
Currently cannot authorize any service provider. When you attempt, it just returns a blank page that only says "Unknown Error"

**Comment by Cleod9** [comment]
Apologies for that, some hotfixes I made have been pending review in the chrome web store since yesterday (and the review process seems to take longer than it did in the past). But I'll be keeping an eye on it, hopefully those changes address the problem

**Comment by Cleod9** [comment]
Chrome store has updated to 0.8.2! If it still gives you authorization issues let me know
